### ISSUE TITLE
Default Alarm Name

### ISSUE THREAD

**Issue by JonHaas** [GorillaSapiens/tauclock#2]
Currently the alarms are all listed as "Description" by default. Now I have 5 alarms called "description". A default name like "6:02 AM" or even sequential "alarm 001" would help manage the list.

**Comment by GorillaSapiens** [comment]
assigning to @JonHaas  to confirm v0.19 fixes this to his satisfaction

**Comment by JonHaas** [comment]
Works great

**Comment by JonHaas** [comment]
👍
